In [2]:
import torch

## Example1:  
y = x^2

In [13]:
x = torch.tensor(3.0, requires_grad=True)

In [14]:
y = x**2

In [15]:
x

tensor(3., requires_grad=True)

In [16]:
y

tensor(9., grad_fn=<PowBackward0>)

In [17]:
y.backward()

In [19]:
x.grad

tensor(6.)

## Example 2 :
1. y = x^2
2. z = sin(y)

In [26]:
x = torch.tensor(4.0, requires_grad=True)

In [27]:
y = x ** 2

In [28]:
z = torch.sin(y)

In [29]:
print("x : ", x)
print("y : ", y)
print("z : ", z)

x :  tensor(4., requires_grad=True)
y :  tensor(16., grad_fn=<PowBackward0>)
z :  tensor(-0.2879, grad_fn=<SinBackward0>)


In [30]:
z.backward()

In [31]:
x.grad

tensor(-7.6613)

In [32]:
y.grad

/tmp/ipykernel_304/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  y.grad


## Example 3 :

1.   z = w.x + b
2.   y_pred = sigmoid(z) = 1 / (1 + e^(-z))
3.   loss = -[y_target * ln(y_pred) + (1 - y_target) * ln(1 - y_pred)]






In [78]:
x = torch.tensor([2., 3., 4.], requires_grad=True)
w = torch.tensor([1.,1.1,2.], requires_grad=True)
b = torch.tensor(1. , requires_grad=True)
y_target = torch.tensor(0.)


In [79]:
z = torch.mul(x,w) + b

In [80]:
z

tensor([3.0000, 4.3000, 9.0000], grad_fn=<AddBackward0>)

In [63]:
def sigmoid(x):
  return 1 / (1 + torch.exp(-x))

In [81]:
y_pred = torch.sigmoid(z)

In [82]:
y_pred

tensor([0.9526, 0.9866, 0.9999], grad_fn=<SigmoidBackward0>)

In [83]:
def Loss(y_hat, y):
  return -(y * torch.log(y_hat) + (1 - y) * torch.log(1 - y_hat))

In [84]:
L = Loss(torch.max(y_pred), y_target)

In [85]:
L

tensor(9.0002, grad_fn=<NegBackward0>)

In [86]:
L.backward()

In [87]:
x.grad

tensor([0.0000, 0.0000, 1.9998])

In [88]:
w.grad

tensor([0.0000, 0.0000, 3.9995])

In [89]:
b.grad

tensor(0.9999)

## Example 4 :

-- Clearing gradients

In [132]:
x = torch.tensor([2., 4., 6., 8.],requires_grad=True)

In [133]:
x

tensor([2., 4., 6., 8.], requires_grad=True)

In [134]:
for _ in range(3):
  y = torch.mean(torch.square(x))
  y.backward()
  print(x.grad)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])
tensor([ 3.,  6.,  9., 12.])


In [137]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

#### Gradients get accumulated with each forward pass or iteration, which is not desirable and we should manually set them to zero after each iteration

In [139]:
for _ in range(3):
  y = torch.mean(torch.square(x))
  y.backward()
  print(x.grad)
  x.grad.zero_()

tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.])


## Disabling gradient tracking whenever tracking is unnecessary

In [3]:
x = torch.tensor(2., requires_grad=True)

In [4]:
x

tensor(2., requires_grad=True)

In [162]:
y = torch.square(x)

In [163]:
y

tensor(4., grad_fn=<PowBackward0>)

In [164]:
y.backward()

In [165]:
x.grad

tensor(4.)

In [9]:
z = x.detach()

In [10]:
z

tensor(2.)

In [11]:
y1 = z ** 2

In [12]:
y1

tensor(4.)

In [13]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [14]:
with torch.no_grad():
  y2 = x ** 2

In [16]:
y2

tensor(4.)

In [17]:
y2.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn