In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
X, y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 23
)

In [ ]:
X

array([[-0.7523056 , -1.30545797],
       [ 1.89022424,  0.1221796 ],
       [-0.11418569,  0.38210847],
       [-1.01716506,  1.17268573],
       [-1.08399662, -0.48974335],
       [-1.55815629, -1.17215372],
       [-0.47563552, -0.95137457],
       [-1.02258085,  0.99150325],
       [ 1.37201743,  1.43003547],
       [ 0.36679816, -1.23162413]])

In [ ]:
X.shape

(10, 2)

In [ ]:
y

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y.shape

(10,)

In [ ]:
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

In [ ]:
X

tensor([[-0.7523, -1.3055],
        [ 1.8902,  0.1222],
        [-0.1142,  0.3821],
        [-1.0172,  1.1727],
        [-1.0840, -0.4897],
        [-1.5582, -1.1722],
        [-0.4756, -0.9514],
        [-1.0226,  0.9915],
        [ 1.3720,  1.4300],
        [ 0.3668, -1.2316]])

In [ ]:
y

tensor([1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):

  def __init__(self,features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  # We can make any transformations here in this method before returning item
  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [ ]:
dataset = CustomDataset(X,y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[4]

(tensor([-1.0840, -0.4897]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True) #Iterable

In [ ]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-1.5582, -1.1722],
        [-1.0226,  0.9915]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.4756, -0.9514],
        [-1.0172,  1.1727]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 0.3668, -1.2316],
        [ 1.8902,  0.1222]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.1142,  0.3821],
        [-0.7523, -1.3055]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.0840, -0.4897],
        [ 1.3720,  1.4300]])
tensor([0, 1])
--------------------------------------------------
