#**Dont try to rerun the code!!!!!**
### Just Go through it

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is available
Using GPU: Tesla T4


### Creating a Tensor

In [3]:
# Using empty
a = torch.empty(2,3)

In [4]:
# Check Type
type(a)

torch.Tensor

In [5]:
# Using Zeros
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using Ones
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
# Using Rand
torch.manual_seed(2) # Manual Seed
torch.rand(4,5)

tensor([[0.6147, 0.3810, 0.6371, 0.4745, 0.7136],
        [0.6190, 0.4425, 0.0958, 0.6142, 0.0573],
        [0.5657, 0.5332, 0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050, 0.3078, 0.9809]])

In [8]:
# Using tensor()
torch.tensor([[2,3,2],[3,4,5]])

tensor([[2, 3, 2],
        [3, 4, 5]])

In [9]:
# Other ways

print("Using arange -> : ", torch.arange(0,20,3)) # Using arange()

print("Using linspace -> :", torch.linspace(2,10,5)) # using linspace()

print("Using eye -> : ", torch.eye(4)) # Using eye()

print("Using full -> : ", torch.full((4,3),10)) # using full()

Using arange -> :  tensor([ 0,  3,  6,  9, 12, 15, 18])
Using linspace -> : tensor([ 2.,  4.,  6.,  8., 10.])
Using eye -> :  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Using full -> :  tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [28]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [30]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

In [31]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [32]:
tensor.device

device(type='cuda', index=0)

In [33]:
# Standard Numpy Indexing

tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [34]:
# Joining Tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [84]:
torch.manual_seed(2)
b = torch.rand((3,4))
b

tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

In [86]:
torch.transpose(b,0,1)

tensor([[0.6147, 0.7136, 0.6142],
        [0.3810, 0.6190, 0.0573],
        [0.6371, 0.4425, 0.5657],
        [0.4745, 0.0958, 0.5332]])

In [88]:
torch.det(tensor)

tensor(-0.)

In [89]:
torch.inverse(tensor)

_LinAlgError: linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.

 ### Arithmetic Opearions

In [36]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [37]:

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single Element Opearions

In [50]:
agg = tensor.sum()
agg_item = agg.item()
print(tensor,'\n')
print('Data value: ',agg_item, '\n','DataType: ', type(agg_item))
print(agg)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

Data value:  92.0 
 DataType:  <class 'float'>
tensor(92.)


In [68]:
a = torch.tensor([[3,4,5],[5,3,6]], dtype=torch.int32)
print(torch.sum(a,dim = 0)) # Column-wise
torch.sum(a, dim  = 1) # Row-wise

tensor([ 8,  7, 11])


tensor([12, 14])

In [74]:
a = a.to(torch.float32)

In [75]:
torch.mean(a)

tensor(4.3333)

### In-Place Operations
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [52]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [104]:
tensor

tensor([[2., 3., 2.],
        [3., 4., 5.]])

In [105]:
tensor.add_(tensor)
tensor

tensor([[ 4.,  6.,  4.],
        [ 6.,  8., 10.]])

## Bridge With NumPy

In [57]:
import numpy as np

In [53]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [55]:
# A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [58]:
n = np.ones(5)
t = torch.from_numpy(n)

In [59]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Special Functions

In [97]:
tensor = torch.tensor([[2,3,2],[3,4,5]], dtype = torch.float32)

In [98]:
torch.log(tensor)

tensor([[0.6931, 1.0986, 0.6931],
        [1.0986, 1.3863, 1.6094]])

In [99]:
torch.exp(tensor)

tensor([[  7.3891,  20.0855,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])

In [100]:
torch.sigmoid(tensor)

tensor([[0.8808, 0.9526, 0.8808],
        [0.9526, 0.9820, 0.9933]])

In [102]:
torch.softmax(tensor,1)

tensor([[0.2119, 0.5761, 0.2119],
        [0.0900, 0.2447, 0.6652]])

In [103]:
torch.relu(tensor)

tensor([[2., 3., 2.],
        [3., 4., 5.]])

In [109]:
t = torch.tensor([-1,-2,2,3])

In [110]:
# In-place Operation
t.relu_()

tensor([0, 0, 2, 3])

## Copying a Tensor

In [111]:
x = torch.rand(2,3)

In [112]:
x

tensor([[0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [114]:
y = x
y

tensor([[0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [115]:
x[0][0] = 0

In [117]:
y
# Changing x --> changes y also

tensor([[0.0000, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [122]:
print(id(x))
print(id(y))
#  Both will be same -- So No copy happening, it just refering to it!

138696905479248
138696905479248


In [123]:
z = x.clone()

In [126]:
print(id(z))
print(id(x))
# Now it is different

138696663781200
138696905479248


In [129]:
import time

size = 10_000
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start

print(f"Time on cpu : {cpu_time}s")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')


start = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start

print(f"Time on gpu : {gpu_time}s")

Time on cpu : 16.55692410469055s
Time on gpu : 0.8628079891204834s


In [130]:
a

tensor([[3., 4., 5.],
        [5., 3., 6.]])

In [131]:
a.flatten()

tensor([3., 4., 5., 5., 3., 6.])

In [132]:
a.reshape(1,1,6)

tensor([[[3., 4., 5., 5., 3., 6.]]])

In [133]:
a.T

tensor([[3., 5.],
        [4., 3.],
        [5., 6.]])

In [138]:
b = torch.rand(226,226,3)

In [139]:
b.permute(2,0,1).shape

torch.Size([3, 226, 226])

In [142]:
b.unsqueeze(1).shape # 1 - position where to add new dimension

torch.Size([226, 1, 226, 3])

In [158]:
b.reshape(1,-1).squeeze(0).shape # (1,226*226*3) --> (2268226*3) = (153228)

torch.Size([153228])

In [159]:
print(226*226*3)

153228
